// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEwX7sE1Gpa_ENx6NrDduLKUtz0-MffJs',
    appId: '1:365360438592:android:d5de7daf280b4949ce6ea5',
    messagingSenderId: '365360438592',
    projectId: 'decor-lens',
    storageBucket: 'decor-lens.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdgkmVfJMxaaszzhRggKIpaYTA7mtoDjs',
    appId: '1:365360438592:ios:293a5306a7e06d14ce6ea5',
    messagingSenderId: '365360438592',
    projectId: 'decor-lens',
    storageBucket: 'decor-lens.firebasestorage.app',
    iosBundleId: 'com.example.decorLens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdgkmVfJMxaaszzhRggKIpaYTA7mtoDjs',
    appId: '1:365360438592:ios:293a5306a7e06d14ce6ea5',
    messagingSenderId: '365360438592',
    projectId: 'decor-lens',
    storageBucket: 'decor-lens.firebasestorage.app',
    iosBundleId: 'com.example.decorLens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIJtbFV43tSr2SB54HvfNX2eL4F32IOqw',
    appId: '1:365360438592:web:488090cb3923c0a0ce6ea5',
    messagingSenderId: '365360438592',
    projectId: 'decor-lens',
    authDomain: 'decor-lens.firebaseapp.com',
    storageBucket: 'decor-lens.firebasestorage.app',
    measurementId: 'G-K96C7427MM',
  );
}
